# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
 #       in_memory:
  #          memory: ~

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost:      15

    providers:
             our_db_provider:
                             entity:
                                    class: AppBundle:User
                                    property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
             anonymous: ~
             pattern:    ^/
             form_login:
                       login_path: login
                       check_path: login
                       default_target_path: /homeopathy
             provider: our_db_provider
             logout:
                    path:   /logout
                    target: /login

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
